name: React.js CI/CD Pipeline 
on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 
jobs:
  build-test-deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build
        run: npm run build

      - name: Run Test
        run: npm test
